#config_version=6

switches:

  #DIRECT SWITCHES
  #switch numbers are labelled in silkscreen on the board

# start J1

  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper

  s_start:
    number: 0-0-3
    tags: start

  s_drain:
    number: 0-0-8

# end J1

# start J5

  s_left_slingshot:
    number: 1-0-16
  s_right_slingshot:
    number: 1-0-17

  s_left_outlane:
    number: 1-0-18
  s_left_inlane:
    number: 1-0-19
  s_right_inlane:
    number: 1-0-20
  s_right_outlane:
    number: 1-0-21
#end J2

# start J3

  s_left_target_1:
    number: 1-0-1
  s_left_target_2:
    number: 1-0-2
  s_left_target_3:
    number: 1-0-3

  s_spinner:
    number: 1-0-8

  s_right_target_1:
    number: 1-0-9
  s_right_target_2:
    number: 1-0-10
  s_right_target_3:
    number: 1-0-11

# end J3

# start J4

  s_right_upper_target_1:
    number: 1-0-31
  s_right_upper_target_2:
    number: 1-0-30

  s_center_target:
    number: 1-0-29
  s_center_eject:
    number: 1-0-28

  s_left_popper:
    number: 1-0-27
  s_right_popper:
    number: 1-0-26

# end J4